---
- include_tasks: "_setup-common.yml"
  when:
    - act == 'setup'
    - target == 'all'

#- include_tasks: "_setup-{{ target }}.yml"
#  when: 
#    - act == "setup"
#    - target in ['hiveserver2', 'hivemetastore']

# this task require group_vars/mysql.yml, group_vars/zookeeper.yml
- include_tasks: "_config-common.yml"
  when:
    - act == 'config'
    - target == 'all'

- include_tasks: "_config-{{ target }}.yml"
  when: 
    - act == "config"
    - target in [ 'statestored', 'catalogd', 'admissiond', 'impalad' ]

- include_tasks: "_start-{{ target }}.yml"
  when: 
    - act == "start"
    - target in [ 'statestored', 'catalogd', 'admissiond', 'impalad' ]

- include_tasks: "_stop-{{ target }}.yml"
  when: 
    - act == "stop"
    - target in [ 'statestored', 'catalogd', 'admissiond', 'impalad' ]
