---
- template:
    src: "{{ item }}.j2"
    dest: "{{ stack_root }}/hadoop/bin/{{ item }}"
    mode: "0755"
  with_items:
    - hdfs
    - yarn

- template: 
    src: "hadoop/{{ item }}.j2"
    # dest: "{{ stack_root }}/hadoop/etc/hadoop/{{ item }}"
    dest: "/etc/hadoop/conf/{{ item }}" 
  with_items:
    - workers
    - hadoop-env.sh
    - yarn-env.sh
    - mapred-env.sh
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
    - mapred-site.xml
    - capacity-scheduler.xml
    - container-executor.cfg
    - log4j.properties
    - rack_topology.sh
    - rack_topology.data

- file:
    path={{ stack_root }}/hadoop/bin/container-executor
    owner=root group=hadoop
    mode=6050