---
airflow_admin_name: "airflow admin"
airflow_admin_id: airflow
airflow_admin_password: airflow

airflow_db_user: airflow
airflow_db_name: airflow
airflow_db_password: airflow

airflow_run_dir: /run/airflow

# airflow.cfg
executor: LocalExecutor
airflow_sql_alchemy_conn: "mysql+pymysql://{{ airflow_db_user }}:{{ airflow_db_password }}@{{ groups['mysql'][0] }}:{{ mysql_port }}/{{ airflow_db_name }}"

airflow_dags_folder: "{{ stack_root }}/airflow/dags"
airflow_plugins_folder: "{{ stack_root }}/airflow/plugins"
airflow_base_log_folder: /var/log/airflow

airflow_webserver_port: 38080

airflow_expose_config: True
airflow_expose_hostname: True
airflow_dag_default_view: tree