---
# Hadoop3 default port info
# https://www.stefaanlippens.net/hadoop-3-default-ports.html

# hadoop basic vars
hadoop_download_path: "https://dlcdn.apache.org/hadoop/common/hadoop-{{ hadoop_version }}"
hadoop_download_filename: "hadoop-{{ hadoop_version }}"

hadoop_log_dir: /var/log/hadoop
hadoop_run_dir: /var/run/hadoop

hadoop_mount_directories:
  - /data

# core-site.xml
fs:
  defaultFS: hdfs://{{ dfs.nameservices }}

# hdfs-site.xml
dfs:
  nameservices: bdp
  replication: 3
  datanode:
    data:
      dir: 
        - /data/hdfs/data
    
    address: "0.0.0.0:50010"

# yarn-site.xml


# container-executor.cfg
yarn.nodemanager.local-dirs: "{{ hadoop_mount_directories | join(',') }}"
banned.users:
  - hdfs
  - yarn
  - mapred
  - bin