---

# hadoop basic vars
hadoop_download_path: "https://dlcdn.apache.org/hadoop/common/hadoop-{{ hadoop_version }}"
hadoop_download_filename: "hadoop-{{ hadoop_version }}"

hadoop_log_dir: /var/log/hadoop
hadoop_run_dir: /var/run/hadoop
hadoop_conf_dir: /etc/hadoop/conf

hadoop_mount_disks:
  - /data

# Hadoop3 default port info
# https://www.stefaanlippens.net/hadoop-3-default-ports.html

# core-site.xml

# hdfs-site.xml
dfs:
  nameservices: bdp
  replication: 3

  hosts_exclude_path: "{{ hadoop_conf_dir }}/dfs.exclude"

  datanode:
    data_sub_dir: /hdfs/data
  namenode:
    name_dir: /hadoop/hdfs/namenode
  journalnode:
    edits_dir: /hadoop/hdfs/journal

yarn:
  resourcemanager:
    nodes_exclude_path: "{{ hadoop_conf_dir }}/yarn.exclude"
  nodemanager:
    local_sub_dir: /yarn/nm-local
    log_sub_dir: /yarn/container-log