---
hive_download_path: "https://dlcdn.apache.org/hive/hive-{{ hive_version }}"
hive_download_filename: "apache-hive-{{ hive_version }}-bin"

db_user: hive
db_name: hive
db_password: hive

hive_log_dir: /var/log/hive
hive_run_dir: /var/run/hive
hive_conf_dir: /etc/hive/conf

# hive-site.xml
hivemetastore_drivername: com.mysql.jdbc.Driver
hivemetastore_port: 9083
hivemetastore_warehouse_dir: /user/hive/warehouse</
hive_auto_convert_join_noconditionaltask_size: 10000000
hive_execution_engine: tez
hive_exec_dynamic_partition_mode: nonstrict

hiveserver2_thrift_port: 10000
hiveserver2_webui_port: 10002

hive_tez_container_size: 1024