---
- name: stop airflow-scheduler
  systemd:
    name: airflow-scheduler
    state: stopped

- name: stop airflow-webserver
  block:
  - systemd:
      name: airflow-webserver
      state: stopped
  - wait_for:
      host: "{{ inventory_hostname }}"
      port: "{{ airflow_webserver_port }}"
      state: stopped