---
- block:
  - name: check installed status
    stat: 
      path: "{{ stack_root }}/apache-airflow-{{ airflow_version }}"
    register: installed
  - import_tasks: _setup.yml
    when: not installed.stat.exists
  when: act == 'setup'

- include_tasks: _config.yml
  when: act in ['config', 'setup']

- include_tasks: _start.yml
  when: act == 'start'
  
- include_tasks: _stop.yml
  when: act == 'stop'

- include_tasks: _restart.yml
  when: act == ['config', 'restart']