---
- name: Register systemd
  block:
  - template: 
      src: "systemd/{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
    with_items:
      - hbase-backup-master.service
  - systemd: 
      daemon_reload: yes