---
- block:
  - import_tasks: _setup.yml
  when: act == 'setup'

- include_tasks: _config.yml
  when: act in ['setup', 'config']

- include_tasks: _createdb.yml
  when: 
    - createdb is defined and createdb
    - db_name is defined
    - db_user is defined
    - db_password is defined

- include_tasks: _start.yml
  when: act == 'start'
  
- include_tasks: _stop.yml
  when: act == 'stop'

- include_tasks: _restart.yml
  when: act in ['restart', 'config']