---
- template:
    src: "{{ item }}.j2"
    dest: "{{ stack_root }}/zookeeper/conf/{{ item }}"
  with_items:
    - zoo.cfg
    - zookeeper-env.sh
    - log4j.properties

- template:
    src: myid.j2
    dest: "{{ zookeeper_data_dir }}/myid"

- template:
    src: zookeeper-client.j2
    dest: /usr/bin/zookeeper-client
    mode: 0755

- include_tasks: restart-zookeeper.yml