---
- name: check file exists
  local_action: stat path="{{ act }}-zookeeper.yml"
  register: file

- name: check installed status
  stat: 
    path: "{{ stack_root }}/{{ zookeeper_download_filename }}"
  register: installed

- include_tasks: "{{ act }}-zookeeper.yml"
  when: file.stat.exists and
        (act == "setup" and not installed.stat.exists) or
        act != "setup"