---
- block:
  - name: check installed status
    stat: 
      path: "{{ stack_root }}/{{ hadoop_download_filename }}"
    register: installed
  - import_tasks: _setup.yml
    when: not installed.stat.exists
  tags: setup

- import_tasks: _config.yml
  tags: 
    - config
    - setup