# tags:
#   - setup
#   - config
#   - start
#   - stop
#   - restart

- block:
  - name: check installed status
    stat: 
      path: "{{ stack_root }}/apache-superset-{{ superset_version }}"
    register: installed
  - import_tasks: _setup.yml
    when: not installed.stat.exists
  tags: setup

- import_tasks: _config.yml
  tags: 
    - setup
    - config

- import_tasks: _start.yml
  tags: start
  
- import_tasks: _stop.yml
  tags: stop

- import_tasks: _restart.yml
  tags: 
    - restart
    - config