---
- name: check file exists
  local_action: stat path="{{ role_path }}/tasks/{{ act }}-superset.yml"
  register: file

- name: check installed status
  stat: 
    path: "{{ stack_root }}/superset-{{ superset_version }}"
  register: installed

- include_tasks: "{{ act }}-superset.yml"
  when: 
    - file.stat.exists
    - (act == "setup" and not installed.stat.exists) or act != "setup"