---
- template:
    src: "{{ item }}.j2"
    dest: "{{ stack_root }}/hadoop/bin/{{ item }}"
    mode: 0755
  with_items:
    - hdfs
    - yarn

- template: 
    src: "{{ item }}.j2"
    dest: "{{ hadoop_conf_dir }}/{{ item }}" 
  with_items:
    - hadoop-env.sh
    - yarn-env.sh
    - mapred-env.sh
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
    - mapred-site.xml
    - capacity-scheduler.xml
    - container-executor.cfg
    - log4j.properties

# - name: Apply config timelineserver
#   template:
#     src: "{{ item }}.j2"
#     dest: "{{ hadoop_conf_dir }}/embedded-yarn-ats-hbase/{{ item }}"
#   with_items:
#     - hbase-env.sh
#     - hbase-site.xml
#     - hadoop-metrics2-hbase.properties
#     - hbase_grant_permissions.sh
#     - hbase-policy.xml
#     - log4j.properties

- file:
    path: "{{ stack_root }}/hadoop/bin/container-executor"
    owner: root
    group: hadoop
    mode: 6050