---
- name: Create user
  user: 
    name: httpfs 
    group: hadoop
    state: present

- file: 
    path: "{{ stack_root }}/hadoop/temp" 
    state: directory
    owner: httpfs 
    group: hadoop 

- file: 
    path: "{{ item }}/httpfs"
    state: directory
    owner: httpfs
    group: hadoop 
  with_items:
    - "{{ hadoop_run_dir }}"
    - "{{ hadoop_log_dir }}"

- name: Register with systemd
  block:
  - template:
      src: "systemd/{{ item }}.service.j2"
      dest: "/etc/systemd/system/{{ item }}.service"
    with_items:
      - httpfs
  - systemd:
      daemon_reload: yes