---
- name: Register with systemd
  block:
  - template: 
      src: systemd/{{ item }}.j2 
      dest: /etc/systemd/system/{{ item }}
    with_items:
      - timelinereader.service
      - timelineserver.service
      - yarn-hbase-master.service
  - systemd: 
      daemon_reload: yes