---
- name: Register with systemd
  block:
  - template:
      src: "systemd/{{ item }}.service.j2"
      dest: "/etc/systemd/system/{{ item }}.service"
    with_items:
      - namenode
      - zkfc
      - resourcemanager
  - systemd:
      daemon_reload: yes