- block:
  - file: 
      path: "{{ hadoop_run_dir }}/hdfs" 
      state: directory
      owner: hdfs
      group: hadoop
  - systemd:
      name: namenode
      state: started
  - systemd:
      name: zkfc
      state: started
  - wait_for: 
      host: "{{ inventory_hostname }}" 
      port: 50070
      state: started