- name: namenode HA status
  block:
    - shell: sudo su hdfs -c 'hdfs haadmin -getServiceState nn1'
      register: result
    - debug: msg='nn1 => {{ result.stdout }}'
    - pause: seconds=1
    - shell: sudo su hdfs -c 'hdfs haadmin -getServiceState nn2'
      register: result
    - debug: msg='nn2 => {{ result.stdout }}'

- name: rm ha status
  block:
    - shell: sudo su yarn -c 'yarn rmadmin -getServiceState rm1'
      register: result
    - debug: msg='rm1 => {{ result.stdout }}'
    - pause: seconds=1
    - shell: sudo su yarn -c 'yarn rmadmin -getServiceState rm2'
      register: result
    - debug: msg='rm2 => {{ result.stdout }}'