---
- block:
  - name: check installed status
    stat: 
      path: "{{ stack_root }}/{{ hadoop_download_filename }}"
    register: installed
  - include_tasks: "_setup-common.yml"
    when: not installed.stat.exists
  when:
    - act == 'setup'
    - target is defined and 
      target == 'all'

- include_tasks: "_config-common.yml"
  when: 
    - act in ['setup', 'config']
    - target is defined and 
      target == 'all'

- include_tasks: "_setup-{{ target }}.yml"
  when: 
    - act == 'setup'
    - target is defined and 
      target in ['namenode', 'datanode', 'journalnode', 'historyserver']

- include_tasks: "_setup-namenode-ha.yml"

- include_tasks: "_start-{{ target }}.yml"
  when: 
    - act in ['start', 'restart']
    - target is defined and 
      target in ['namenode', 'datanode', 'journalnode']

- include_tasks: "_stop-{{ target }}.yml"
  when: 
    - act in ['stop', 'restart']
    - target is defined and 
      target in ['namenode', 'datanode', 'journalnode']

- include_tasks: _status.yml
  when: 
    - act == 'status'