---
- block:
  - name: check installed status
    stat: 
      path: "{{ stack_root }}/{{ zeppelin_download_filename | first }}"
    register: installed
  - include_tasks: _setup.yml
    #when: not installed.stat.exists
  when: act == 'setup'

- import_tasks: _config.yml
  when: act in ['setup', 'config']

- import_tasks: _start.yml
  when: act == 'start'
  
- import_tasks: _stop.yml
  when: act == 'stop'