---
- block:
  - name: Check if java is installed 
    shell: java -version
    register: installed_jdk
    failed_when: False
    
  - name: Install openjdk
    import_tasks: _setup.yml
    when: installed_jdk.rc != 0
  when: act == 'setup'