- block:
  - name: check installed status
    stat: 
      path: "{{ stack_root }}/{{ tez_download_filename }}"
    register: installed
  - include_tasks: "_setup.yml"
    when: not installed.stat.exists
  when:
    - act == 'setup'

- include_tasks: "_config.yml"
  when: act == ['setup', 'config']