---
- name: Create airflow schema
  hosts: mariadb
  become: yes
  gather_facts: false
  vars_files:
    - group_vars/airflow.yml
  tasks:
  - include_role:
      name: mariadb
      apply:
        tags: createdb
  tags: setup

- hosts: airflow
  become: yes
  vars_files:
    - group_vars/mariadb.yml
  roles:
    - common
    - python
    - airflow