---
- hosts: hadoop
  become: yes
  vars_files:
    - group_vars/zookeeper.yml
    - group_vars/tez.yml
  vars:
    act: setup
    target: all
  roles:
    - common
    - java
    - hadoop

- hosts: journalnode
  become: yes
  vars:
    act: setup
    target: journalnode
  roles: 
    - hadoop

- hosts: namenode
  become: yes
  vars:
    act: setup
    target: namenode
  roles: 
    - hadoop

- hosts: historyserver
  become: yes
  vars:
    act: setup
    target: historyserver
  roles: 
    - hadoop

- hosts: datanode
  become: yes
  vars:
    act: setup
    target: datanode
  roles: 
    - hadoop

- import_playbook: httpfs-setup.yml

- import_playbook: hadoop-ha.yml

- import_playbook: spark-setup.yml

- import_playbook: tez-setup.yml