---
- hosts: journalnode
  become: yes
  serial: 1
  vars:
    act: start
    target: journalnode
  roles: 
    - hadoop

- hosts: namenode
  become: yes
  serial: 1
  vars:
    act: start
    target: namenode
  roles: 
    - hadoop

- hosts: datanode
  become: yes
  serial: 1
  vars:
    act: start
    target: datanode
  roles: 
    - hadoop