---
- hosts: hadoop
  become: yes
  vars_files:
    - group_vars/zookeeper.yml
  roles:
    - common
    - java
    - hadoop-common
  when: component == "all" or 
        component == "common"

- hosts: journalnode
  become: yes
  roles:
    - journalnode
  when: component == "all" or 
        component == "journalnode"

- hosts: namenode
  become: yes
  roles:
    - hadoop-namenode
  when: component == "all" or 
        component == "namenode"

- hosts: datanode
  become: yes
  roles:
    - hadoop-datanode
  when: component == "all" or 
        component == "datanode"