---
- hosts: appmaster
  become: yes
  vars_files:
    - group_vars/hue.yml
    - group_vars/hadoop.yml
    - group_vars/mysql.yml
    - group_vars/hive.yml
    - group_vars/spark.yml
    - group_vars/zookeeper.yml
  vars:
    act: config
  roles:
    - hue