---
- hosts: kafka
  become: yes
  vars_files:
    - group_vars/zookeeper.yml
  roles:
    - common
    - java
    - kafka

- hosts: appmaster
  vars_files:
    - group_vars/zookeeper.yml
    - group_vars/kafka.yml
  roles:
    - common
    - java
    - kafka