---
- hosts: kafka
  become: yes
  vars_files:
    - group_vars/zookeeper.yml
  vars:
    act: setup
    target: kafka
  roles:
    - common
    - java
    - kafka

- hosts: appmaster
  vars_files:
    - group_vars/zookeeper.yml
    - group_vars/kafka.yml
  vars:
    act: setup
    target: kafka
  roles:
    - common
    - java
    - kafka