---
- hosts: kafka_confluent
  become: yes
  vars_files:
    - group_vars/kafka.yml
  vars:
    act: setup
    target: kafka-ui
  roles:
    - kafka

- import_playbook: kafka-ui-config.yml

- import_playbook: schema-registry-config.yml