---
- name: Create superset schema
  hosts: mariadb
  become: yes
  gather_facts: false
  vars_files:
    - group_vars/superset.yml
  tasks:
    - include_tasks: roles/mariadb/tasks/createdb-mariadb.yml
      when: act == "setup"

- hosts: superset
  become: yes
  vars_files:
  roles:
    - common
    - python
    - superset