---
- name: Create superset schema
  hosts: mariadb
  become: yes
  gather_facts: false
  vars_files:
    - group_vars/superset.yml
  vars:
    createdb: True
    db_user: "{{ superset_db_user }}"
    db_name: "{{ superset_db_name }}"
    db_password: "{{ superset_db_password }}"
  roles:
    - mariadb
  when: act == 'setup'

- hosts: superset
  become: yes
  vars_files:
    - group_vars/mariadb.yml
  roles:
    - common
    - python
    - superset