---
- name: Create superset schema
  hosts: mariadb
  become: yes
  gather_facts: false
  vars_files:
    - group_vars/superset.yml
  vars:
    createdb: True
  roles:
    - mariadb
  when: act == 'setup'

- hosts: superset
  become: yes
  vars_files:
    - group_vars/mariadb.yml
  roles:
    - common
    - python
    - superset