- name: test
  hosts: hadoop
  become: yes
  gather_facts: false
  # vars:
  #   createdb: True
  #   db_user: "test"
  #   db_name: "test"
  #   db_password: "test"
  # roles:
  #   - mysql
  tasks:
  - alternatives:
      name: "{{ item.name }}"
      link: "{{ item.link }}"
      path: "{{ item.path }}"
      priority: 20
    loop:
      - {
        name: hive,
        link: /usr/bin/hive,
        path: "{{ stack_root }}/hive/bin/hive"
      }
      - {
        name: beeline,
        link: /usr/bin/beeline,
        path: "{{ stack_root }}/hive/bin/beeline"
      }