---
- template:
    src: "{{ item }}.j2"
    dest: "{{ stack_root }}/spark/conf/{{ item }}"
  with_items:
    - workers
    - spark-env.sh
    - spark-defaults.conf
    - log4j2.properties

- name: Link hive-site.xml to spark
  file:
    src: "{{ stack_root }}/hive/conf/hive-site.xml"
    dest: /etc/spark/conf/hive-site.xml
    state: link
    owner: root
    group: root