---
- name: Link hive conf and spark
  file:
    src: "{{ stack_root }}/hive/conf/hive-site.xml"
    dest: /etc/spark/conf/hive-site.xml
    state: link
    owner: root
    group: root

# - name: remove hive-2.3.9 jar in spark jars dir
#   file:
#     path: "{{ stack_root }}/spark/jars/{{ item }}"
#     state: absent
#   with_items:
#     - hive-beeline-2.3.9.jar
#     - hive-cli-2.3.9.jar
#     - hive-common-2.3.9.jar
#     - hive-exec-2.3.9-core.jar
#     - hive-jdbc-2.3.9.jar
#     - hive-llap-common-2.3.9.jar
#     - hive-metastore-2.3.9.jar
#     - hive-serde-2.3.9.jar
#     - hive-service-rpc-2.3.9.jar
#     - hive-shims-0.23-2.3.9.jar
#     - hive-shims-2.3.9.jar
#     - hive-shims-common-2.3.9.jar
#     - hive-shims-scheduler-2.3.9.jar

# - name: Link hive jars and spark
#   file:
#     src: "{{ stack_root }}/hive/lib/{{ item }}"
#     dest: "{{ stack_root }}/spark/jars/{{ item }}"
#     state: link
#     owner: root
#     group: root
#     force: yes
#   with_items:
#     - hive-beeline-3.1.3.jar
#     - hive-cli-3.1.3.jar
#     - hive-common-3.1.3.jar
#     - hive-exec-3.1.3.jar
#     - hive-jdbc-3.1.3.jar
#     - hive-llap-common-3.1.3.jar
#     - hive-metastore-3.1.3.jar
#     - hive-serde-3.1.3.jar
#     - hive-service-rpc-3.1.3.jar
#     - hive-shims-0.23-3.1.3.jar
#     - hive-shims-3.1.3.jar
#     - hive-shims-common-3.1.3.jar
#     - hive-shims-scheduler-3.1.3.jar