---
- name: Create user
  user:
    name: spark
    group: hadoop
    state: present

- name: Install spark
  block:
  - get_url:
      url: "{{ spark_download_path }}/{{ spark_download_filename }}.tar.gz"
      dest: /tmp/
  - unarchive:
      src: "/tmp/{{ spark_download_filename }}.tgz"
      dest: "{{ stack_root }}"
      copy: no
      owner: root
      group: root
  - file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/tmp/{{ spark_download_filename }}.tgz"

- name: Link installed zookeeper
  block:
  - file:
      path: /etc/zookeeper
      state: directory
      owner: root
      group: root
  - file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
      owner: root
      group: root
    loop:
      # spark install directory link
      - { 
        src: "{{ stack_root }}/{{ spark_download_filename }}", 
        dest: "{{ stack_root }}/spark" 
      }
      # spark config link
      - { 
        src: "{{ stack_root }}/spark/conf", 
        dest: "{{ spark_conf_dir }}"
      }

- file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: spark
    group: hadoop
  with_items:
    - "{{ spark_log_dir }}"
    - "{{ zookeeper_run_dir }}"
    - "{{ zookeeper_data_dir }}"

# move all hadoop component
- copy:
    src=hadoop/spark-{{ spark_version_only }}-yarn-shuffle.jar
    dest={{ stack_root }}/hadoop/share/hadoop/yarn/lib/