---
- name: Create hadoop group
  group:
    name: hadoop
    state: present

- name: Add user to hadoop group
  user:
    name: "{{ general_user }}"
    groups: hadoop
    append: true

- name: Create required dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ stack_root }}"
    - /data

- name: Create cluster environment file
  file:
    path: "/etc/profile.d/{{ cluster_env }}"
    state: touch
    mode: '0644'
