---
- name: Create hadoop group
  group:
    name: hadoop
    state: present

- name: Add user to hadoop group
  user:
    name: "{{ general_user }}"
    groups: hadoop
    append: true

- name: Create stack root dir
  file:
    path: "{{ stack_root }}"
    state: directory
    owner: root
    group: root

- file:
    path: /data
    state: directory
    owner: root
    group: root