---
- name: Install kafka connect
  block:
  - get_url:
      url: "{{ kafka_connect_download_path }}/{{ kafka_connect_download_filename | join('.') }}"
      dest: /tmp/
  - unarchive:
      src: "/tmp/{{ kafka_connect_download_filename | join('.') }}"
      dest: "{{ stack_root }}"
      copy: no
      owner: root
      group: root
  - file:
      path: "/tmp/{{ kafka_connect_download_filename | join('.') }}"
      state: absent

- name: Link installed kafka connect
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: root
    group: root
  loop:
    # kafka connect install directory link
    - { 
      src: "{{ stack_root }}/{{ kafka_connect_download_filename | first }}", 
      dest: "{{ stack_root }}/kafka-confluent" 
    }

- name: Create kafka connect required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: kafka
    group: hadoop
  with_items: 
    - "{{ kafka_log_dir }}"
    - "{{ kafka_connect_plugin_path }}"

- name: Register with systemd
  block:
  - template:
      src: systemd/{{ item }}.j2
      dest: /etc/systemd/system/{{ item }}
    with_items:
      - kafka-connect.service
      - schema-registry.service
  - systemd:
      daemon_reload: yes