---
- name: Create kafka ui directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: kafka
    group: hadoop
  with_items: 
    - "{{ stack_root }}/kafka-ui-{{ kafka_ui_version }}"

- name: Link kafka ui directory
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: root
    group: root
  loop:
    - { 
      src: "{{ stack_root }}/kafka-ui-{{ kafka_ui_version }}", 
      dest: "{{ stack_root }}/kafka-ui" 
    }

- name: Install kafka UI
  get_url:
    url: "{{ kafka_ui_download_path }}/{{ kafka_ui_download_filename }}"
    dest: "{{ stack_root }}/kafka-ui/"

- name: Register with systemd
  block:
  - template:
      src: systemd/{{ item }}.j2
      dest: /etc/systemd/system/{{ item }}
    with_items:
      - kafka-ui.service
  - systemd:
      daemon_reload: yes