---
- name: start kafka connect
  block:
  - systemd:
      name: kafka-connect
      state: started
  - wait_for:
      host: "{{ inventory_hostname }}"
      port: "{{ kafka_connect_port }}"
      state: started