---
- block:
  - name: check installed status kafka
    stat: 
      path: "{{ stack_root }}/{{ kafka_download_filename }}"
    register: installed_kafka
  - import_tasks: _setup-kafka.yml
    when: not installed_kafka.stat.exists
  when: 
    - act == 'setup'
    - target == 'kafka'

- block:
  - name: check installed status kafka connect
    stat: 
      path: "{{ stack_root }}/{{ kafka_connect_download_filename | first }}"
    register: installed_kafka_connect
  - import_tasks: _setup-kafka-connect.yml
    when: not installed_kafka_connect.stat.exists
  when: 
    - act == 'setup'
    - target == 'kafka_connect'

- include_tasks: _config-{{ target }}.yml
  when: 
    - act in ['setup', 'config']
    - target in ['kafka', 'kafka_connect']

- include_tasks: _start-{{ target }}.yml
  when: 
    - act == 'start'
    - target in ['kafka', 'kafka_connect']
  
- include_tasks: _stop-{{ target }}.yml
  when: 
    - act == 'stop'
    - target in ['kafka', 'kafka_connect']
