---
- block:
  - name: check installed status
    stat: 
      path: "{{ stack_root }}/{{ kafka_download_filename }}"
    register: installed
  - import_tasks: _setup.yml
    when: not installed.stat.exists
  when: act == 'setup'

- include_tasks: _config.yml
  when: act in ['setup', 'config']

- include_tasks: _start.yml
  when: act == 'start'
  
- include_tasks: _stop.yml
  when: act == 'stop'

- include_tasks: _restart.yml
  when: act in ['restart', 'config']